name: Automatic Pull
on:
  push:
    branches: [main]
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ProjectNebulus
            git pull
            pm2 restart ProjectNebulus
            echo "Job Completed"
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY}}

