name: Black Code Formatter

on: [push]

jobs:
  Black-Code-Formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "."


    
